spring:
  profiles:
    include: druid
  datasource:
    classPath: src/main/resources/jdbc/mybatis-generator-core-1.3.7.jar
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ZtyLCmM2cPWzPcfX
    #    jdbc_url: jdbc:mysql://42.193.148.230:3306/soc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true
    url: jdbc:mysql://42.193.148.230:3306/soc?serverTimezone=UTC
    username: soc
    project: src/main/java
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#这个是使用日志显示
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: cn.soc.securityoperationscenter.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#配置端口号
server:
  port: 8080
  ssl:
    key-store: classpath:device-safety.cn.jks
#    key-password: 5ox73308o3y
    key-store-type: JKS
#    key-store-provider:
#    key-alias: tomcat
    key-store-password: 5ox73308o3y

#配置分页插件
pagehelper:
  helperDialect=mysql






